server:
  port: 8080

spring:
  application:
    name: api-gateway
  cloud:
    config:
      uri: http://localhost:8888
      username: config-user
      password: config-pass
  data:
    redis:
      host: localhost
      port: 6379
      database: 3

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

jwt:
  secret: z1vY0wDdS6O0nXBjMRwWTwFjM0Hg7BPK3DJ5rZL84Sk=
