server:
  port: 8082

spring:
  application:
    name: ms-account
  datasource:
    url: jdbc:postgresql://localhost:5432/unitech_account
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
