server:
  port: 8081

spring:
  application:
    name: ms-auth
  datasource:
    url: jdbc:postgresql://localhost:5432/unitech_auth
    username: postgres
    password: 123
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  data:
    redis:
      host: localhost
      port: 6379
      database: 0
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest

jwt:
  secret: mySecretKey
  expiration: 86400

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/