server:
  port: 8085

spring:
  application:
    name: ms-bff
  data:
    redis:
      host: localhost
      port: 6379
      database: 2

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/