server:
  port: 8084

spring:
  application:
    name: ms-currency
  data:
    redis:
      host: localhost
      port: 6379
      database: 1

currency:
  cache:
    ttl: 300

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/